### ISSUE TITLE
Libary throws an error if number in string is larger than Int32

### ISSUE THREAD

**Issue by th-joerger** [GihanSoft/NaturalStringComparer#3]
Stacktrace:

```
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at GihanSoft.String.NaturalComparer.GetNumber(ReadOnlySpan`1 span, Int32& number)
   at GihanSoft.String.NaturalComparer.Compare(ReadOnlySpan`1 x, ReadOnlySpan`1 y, StringComparison stringComparison)
   at GihanSoft.String.NaturalComparer.Compare(String x, String y)
```

Compared strings:

1: "19015611190635G"
2: "13808910990635X"

**Comment by GihanSoft** [comment]
@th-joerger tanks for your issue. now it fixed. I'll upload Nuget in few minutes.

**Comment by th-joerger** [comment]
@GihanSoft thanks for the quick fix. I tested and it works, but is a lot slower than before (I have a very long list view to sort). Might I suggest you use [ulong.TryParse](https://learn.microsoft.com/en-us/dotnet/api/system.uint64.tryparse?view=net-8.0) instead of handling the exception? It is much faster, because it internally works without throwing an exception.

**Comment by GihanSoft** [comment]
@th-joerger fixed and merged.
can you give me new feedback of performance? maybe `ulong.TryParse()` is also slower than `long.TryParse()` or `int.TryParse()`

**Comment by th-joerger** [comment]
Thank you again. Performance is much better. Before I got ~50k handled exceptions for a list of around 5k entries. Now it works seamless.

I don't think performance is an issue between the different TryParse methods, as they [are implemented](https://referencesource.microsoft.com/#mscorlib/system/number.cs,1081) using the same [backend function](https://referencesource.microsoft.com/#mscorlib/system/number.cs,9a5e26b13c916503).

**Comment by GihanSoft** [comment]
OK. Tanks again for mentioning long num bug and suggesting `TryParse`
