### ISSUE TITLE
Invalid comparison of long numbers

### ISSUE THREAD

**Issue by ltetak** [GihanSoft/NaturalStringComparer#7]
There is a problem when comparing small and big numbers. GetNumber returns ulong for small numbers and BigInteger for really big numbers. But these two types do not play along nicely so if you compare one with the the other it will crash here

https://github.com/GihanSoft/NaturalStringComparer/blob/a6b7e21084aa2d6bb68224d163e6829888b37c39/src/NaturalStringComparer/NaturalComparer.cs#L87

One solution could be to unify these two types (convert to BigInteger) before comparing.

**Comment by GihanSoft** [comment]
Very good point. I'll fix this as soon as I'm free. Tanks
